---
- hosts: linuxclient1
  become: true
  become_user: root
  tasks:
    - name: Install yum-utils (use the yum module)
      yum:
        name: yum-utils
        state: present

    - name: Install Docker SDK for Python
      pip:
        name: docker
      become_user: root  # Use 'become_user' to run the task as root

    # Other tasks...

- name: Deploy Docker Container
  hosts: 192.168.7.203
  become: true
  
  tasks:
    - name: Debug Python interpreter version
      debug:
        var: ansible_python.version

    - name: Pull image and create container using docker_container
      docker_container:
        name: tomcat_devops
        image: jklipton/devops:latest
        state: started
        tty: true
        auto_remove: true
        ports:
          - "8080:8080"

    - name: logout of Dockerhub
      docker_login:
        state: absent
