---

- name: Install and Deploy docker on linuxclient1

  hosts: 192.168.7.203

  become: true

  become_user: root



  tasks:

    - name: Install yum-utils (use the yum module)

      yum:

        name: yum-utils

        state: present



    - name: Download Docker repository file using the get_url

      shell: sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo



    - name: Install Docker packages (engine) using yum module

      yum:

        name:

          - docker-ce

          - docker-ce-cli

          - containerd.io

          - docker-buildx-plugin

          - docker-compose-plugin

        state: present



    - name: Start Docker service using the systemd module

      systemd:

        name: docker

        state: started

        enabled: yes



    - name: Install python3 and python3-pip

      yum:

        name:

          - python3

          - python3-pip

        state: present



    - name: Ensure python3-pip is installed

      ansible.builtin.raw: test -e /usr/bin/pip || (curl -s https://bootstrap.pypa.io/get-pip.py -o /tmp/get-pip.py && python /tmp/get-pip.py)



    - name: Install Python

      yum:

        name:

          - python

        state: present



    - name: Download get-pip.py

      get_url:

        url: https://bootstrap.pypa.io/pip/2.7/get-pip.py

        dest: /tmp/get-pip.py

   

   

    - name: Install specific version of pip

      ansible.builtin.shell:  python -m pip install --upgrade pip==20.3.4



    - name: Install docker-SDK

      pip:

        name: docker

        executable: /usr/bin/pip



- name: Deploy Container

  hosts: 192.168.7.203

  become: true



  tasks:

    - name: Install required Python libraries

      pip:

        name:

          - docker



    - name: Set Python interpreter for Ansible

      ansible.builtin.set_fact:

        ansible_python_interpreter: /usr/bin/python3



    - name: Install docker library

      pip:

        name: docker



    - name: Pull image and create the container using docker_container

      docker_image:

        name: brianbudowick/devopsfinal:latest

        source: pull



    - name: Start the container using docker_container

      docker_container:

        name: tomcat_devops

        image: brianbudowick/devopsfinal:latest

        state: started

        tty: true

        auto_remove: true

        ports:

          - "8080:8080"



    - name: Log out of DockerHub

      docker_login:

        state: absent
